{% set version = "0.8.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-correlation
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/correlation_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/correlation/correlation_{{ version }}.tar.gz
  sha256: 1e38778b797b089ab76b84d4dbd08906db822cb3881452b8069bf1bde9c1bb2c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bayestestr >=0.9.0
    - r-effectsize >=0.4.4
    - r-insight >=0.13.2
    - r-parameters >=0.12.0
  run:
    - r-base
    - r-bayestestr >=0.9.0
    - r-effectsize >=0.4.4
    - r-insight >=0.13.2
    - r-parameters >=0.12.0

test:
  commands:
    - $R -e "library('correlation')"           # [not win]
    - "\"%R%\" -e \"library('correlation')\""  # [win]

about:
  home: https://easystats.github.io/correlation/
  license: GPL-3.0-only
  summary: Lightweight package for computing different kinds of correlations, such as partial correlations, Bayesian correlations, multilevel correlations, polychoric correlations, biweight correlations, distance correlations and more. Relies on the easystats ecosystem (Lüdecke, Waggoner & Makowski (2019) <doi:10.21105/joss.01412>).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: correlation
# Type: Package
# Title: Methods for Correlation Analysis
# Version: 0.2.0
# Authors@R: c( person("Dominique", "Makowski", email = "dom.makowski@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-5375-9967")), person("Daniel", "Ludecke", role = c("aut"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206")), person("Mattan S.", "Ben-Shachar", role = c("ctb"), email = "matanshm@post.bgu.ac.il", comment = c(ORCID = "0000-0002-4287-4801")), person("Indrajeet", "Patil", role = c("ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531")) )
# Maintainer: Dominique Makowski <dom.makowski@gmail.com>
# URL: https://easystats.github.io/correlation/
# BugReports: https://github.com/easystats/correlation/issues
# Description: Lightweight package for computing different kinds of correlations, such as partial correlations, Bayesian correlations, multilevel correlations, polychoric correlations, biweight correlations, distance correlations and more. Relies on the easystats ecosystem (Ludecke, Waggoner & Makowski (2019) <doi:10.21105/joss.01412>).
# Imports: stats, insight (>= 0.8.0), bayestestR (>= 0.5.0), parameters (>= 0.5.0), effectsize (>= 0.2.0)
# Suggests: BayesFactor, dplyr, energy, ggcorrplot, ggplot2, Hmisc, knitr, lme4, polycor, ppcor, psych, rmcorr, testthat, tidyr, covr, rstanarm, rmarkdown, see, WRS2
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-04-09 08:30:42 UTC; domma
# Author: Dominique Makowski [aut, cre] (<https://orcid.org/0000-0001-5375-9967>), Daniel Ludecke [aut] (<https://orcid.org/0000-0002-8895-3206>), Mattan S. Ben-Shachar [ctb] (<https://orcid.org/0000-0002-4287-4801>), Indrajeet Patil [ctb] (<https://orcid.org/0000-0003-1995-6531>)
# Repository: CRAN
# Date/Publication: 2020-04-09 08:50:12 UTC
